### ISSUE TITLE
Rocket Clips into the ground

### ISSUE THREAD

**Issue by VeryCrazyCat** [Stardom-game/Stardom#6]
At launch, the rocket clips into the ground if the rocket height is not a multiple of 32.
This is due to the joints system, which assigns positions not velocity to the parts.
This prevents pymunk from calculating collisions accurately.
As such, the joints system needs redoing - maybe put the rocket all into one body at launch and split it up?

**Comment by Fluffik3666** [comment]
can we just offset the joints to eg. ground + 2 if height / 32 == true

**Comment by Fluffik3666** [comment]
it's a dumb idea but I can't really do anything in-depth rn
