### ISSUE TITLE
Fetch music/pictures from a cdn

### ISSUE THREAD

**Issue by Fluffik3666** [Stardom-game/Stardom#7]
Make a cdn, we can cut down on game size
I can make it and (try) run it locally in my home lab

**Comment by VeryCrazyCat** [comment]
I think I would prefer to keep the game offline though

**Comment by VeryCrazyCat** [comment]
Also if your home Wi-Fi goes down then that's everyone's music gone

**Comment by Fluffik3666** [comment]
Yeah but 18mb

**Comment by Fluffik3666** [comment]
We can fetch media on first game launch

**Comment by Fluffik3666** [comment]
> Also if your home Wi-Fi goes down then that's everyone's music gone

My homelab is on a UPS and I stage production so updates and stuff only happened that night

**Comment by Fluffik3666** [comment]
I'll build and run the cdn in 31st

I get back late 30th from Amsterdam

**Comment by VeryCrazyCat** [comment]
This will no longer be implemented
